vaadin/vaadin-select-flow

vaadin-select-flow-demo/pom.xml
vaadin-select-flow-integration-tests/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-select-flow/7)

Fix dependencies versions (Replace LATEST with SNAPSHOT version)

---

vaadin-select-flow-demo/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-select-flow/8)

Use compile scope for the logger dependency

---

pom.xml
vaadin-select-flow-demo/pom.xml
vaadin-select-flow-integration-tests/pom.xml
vaadin-select-flow-testbench/pom.xml
vaadin-select-flow/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-select-flow/10)

Update to next minor and flow version

---

vaadin-select-flow-integration-tests/src/test/java/com/vaadin/flow/component/select/test/ItemLabelGeneratorIT.java
vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/Select.java
vaadin-select-flow/src/test/java/com/vaadin/flow/component/select/SelectTest.java

Fixes #12
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-select-flow/17)

Fix setItemLabelGenerator() does not set the labels in opened state. #12

---

pom.xml
vaadin-select-flow-integration-tests/pom-bower-mode.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-select-flow/27)

Update to 2.0 and add bower mode

---

vaadin-select-flow/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-select-flow/28)

Update bower versions

---

pom.xml
vaadin-select-flow-integration-tests/pom-bower-mode.xml
vaadin-select-flow-integration-tests/pom.xml
vaadin-select-flow-integration-tests/src/test/java/com/vaadin/flow/component/select/test/AbstractSelectIT.java
vaadin-select-flow-testbench/pom.xml
vaadin-select-flow-testbench/src/main/java/com/vaadin/flow/component/select/testbench/SelectElement.java

Use common interfaces from testbench-core
Add specific dependency for other components TBElements
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-select-flow/29)

Remove vaadin-components-testbench

---

vaadin-select-flow/pom.xml
vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/generated/GeneratedVaadinSelect.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-select-flow/31)

Update WC versions

---

vaadin-select-flow/pom.xml
vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/generated/GeneratedVaadinSelect.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-select-flow/32)

Bump vaadin-select wc dependency to 2.1.2

---

vaadin-select-flow/pom.xml
vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/generated/GeneratedVaadinSelect.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-select-flow/33)

Bump versions, update WC dependency to 2.1.3

---

vaadin-select-flow/pom.xml
vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/generated/GeneratedVaadinSelect.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-select-flow/34)

Bump versions, update WC dependency to 2.1.5

---

vaadin-select-flow-demo/src/main/java/com/vaadin/flow/component/select/SelectView.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-select-flow/42)

Improve demos by adding theme variants

---

vaadin-select-flow-integration-tests/src/main/java/com/vaadin/flow/component/select/examples/TestReattachView.java
vaadin-select-flow-integration-tests/src/test/java/com/vaadin/flow/component/select/test/DetachIT.java
vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/Select.java

Fixes #43
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-select-flow/45)

Removed workaround for vaadin/vaadin-select#180

---

vaadin-select-flow/pom.xml
vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/generated/GeneratedVaadinSelect.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-select-flow/48)

Bump web component version to 2.1.6

---

vaadin-select-flow/src/main/resources/META-INF/resources/frontend/selectConnector.js

Connected to vaadin/components-team-tasks#479
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-select-flow/39)

Improve error handling in connector: wrap with try catch

---

vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/Select.java
vaadin-select-flow/src/test/java/com/vaadin/flow/component/select/SelectTest.java

Fix for ItemRenderer when ItemLabelGenerator is used

---

vaadin-select-flow/src/main/resources/META-INF/resources/frontend/selectConnector.js

Use removeChild instead of remove for IE11

---

vaadin-select-flow/src/main/resources/META-INF/resources/frontend/selectConnector.js

Align with https://github.com/vaadin/vaadin-grid-flow/pull/847
Connected to vaadin/vaadin-combo-box-flow#313

Fix wrapped initLazy definition

---

vaadin-select-flow/pom.xml
vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/generated/GeneratedVaadinSelect.java

This is a PR for `2.0` branch to get demos delivered. Will submit another one to `master`.

Bump web component version to 2.1.7

---

vaadin-select-flow-demo/src/main/java/com/vaadin/flow/component/select/SelectView.java

This issue is for users to be able to use code correctly by copy-pasting
Depends on https://github.com/vaadin/flow/pull/8199/files

Add missing method to Vaadin Select field

---

pom.xml
vaadin-select-flow-demo/pom.xml
vaadin-select-flow-integration-tests/pom-bower-mode.xml
vaadin-select-flow-integration-tests/pom.xml
vaadin-select-flow-testbench/pom.xml
vaadin-select-flow/pom.xml
vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/generated/GeneratedVaadinSelect.java

* Bump snapshot version
* Bump flow-component-base (2.3-SNAPSHOT)
* Bump WC dependency
* Bump webjar dependencies
Part of vaadin/components-team-tasks#534

Bump versions for V14.3

---

vaadin-select-flow-demo/src/main/java/com/vaadin/flow/component/select/SelectView.java

Co-authored-by: Anastasia Smirnova <anastsmirnova96@gmail.com>

[cherry-pick] Add missing method to Vaadin Select field (#63)

---

vaadin-select-flow/pom.xml
vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/Select.java
vaadin-select-flow/src/test/java/com/vaadin/flow/component/select/data/SelectListDataViewTest.java

Fixes https://github.com/vaadin/flow/issues/8345 for Select component
Depends on https://github.com/vaadin/flow/pull/8453

Implement SizeChangeEvent handling for DataView #8345

---

vaadin-select-flow-demo/src/main/java/com/vaadin/flow/component/select/SelectView.java
vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/data/SelectDataView.java
vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/data/SelectListDataView.java
vaadin-select-flow/src/test/java/com/vaadin/flow/component/select/data/SelectListDataViewTest.java

Address DX feedback for data views #8497

---

vaadin-select-flow-demo/src/main/java/com/vaadin/flow/component/select/SelectView.java
vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/Select.java
vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/data/SelectDataViewImpl.java
vaadin-select-flow/src/test/java/com/vaadin/flow/component/select/data/SelectDataViewImplTest.java
vaadin-select-flow/src/test/java/com/vaadin/flow/component/select/data/SelectListDataViewTest.java

Use setDataSource for setting data.

---

vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/Select.java
vaadin-select-flow/src/test/java/com/vaadin/flow/component/select/SelectTest.java

Always create data view.
Make exception clearer on what to do.

Update DataView creation

---

vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/Select.java
vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/data/SelectDataViewImpl.java
vaadin-select-flow/src/test/java/com/vaadin/flow/component/select/data/SelectDataViewImplTest.java

Depends on https://github.com/vaadin/flow/pull/8581

Configure identity provider for a components through the Data View

---

vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/Select.java
vaadin-select-flow/src/test/java/com/vaadin/flow/component/select/data/SelectDataViewTest.java

Corresponds to https://github.com/vaadin/flow/pull/8874

Filter support in Data View API

---

vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/Select.java
vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/generated/GeneratedVaadinSelect.java
vaadin-select-flow/src/test/java/com/vaadin/flow/component/select/SelectTest.java

Don't set initial value if Element has property
